### PR TITLE
Introduces several refactor points and support for barcode-only AbIDs

### PR DESCRIPTION
**Pull request by jrgriffiniii**

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
There are still some failing tests for this, but this addresses a multitude of refactoring and DRY-deduplication. Further, this includes functionality which completes the MARC-linked AbID generation, as well as the generation for AbIDs used just as barcodes.

**Comment by jrgriffiniii** [comment]
f774d2c has every test passing but one system spec for my local environment.

**Comment by jrgriffiniii** [comment]
There were a number of regressions which were introduced within these commits, however, this should address these (as well as some minor bug fixes).

**Comment by tpendragon** [comment]
I can't adequately review this, the diff is too big and there are too many commits. As we're under a timeline I'm going to approve it assuming CI checks out.

**Pull request merged**
